name: Build Android App with Buildozer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install required dependencies
      run: |
        # Install necessary dependencies
        sudo apt-get update
        sudo apt-get install -y python3-pip python3-dev build-essential curl unzip
        sudo apt-get install -y openjdk-8-jdk  # Installing OpenJDK 8 for compatibility with NDK 21+

    - name: Install Buildozer and dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install buildozer

    - name: Install Android SDK and NDK
      run: |
        # Install Android SDK command-line tools
        curl -sS https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -o commandlinetools.zip
        unzip commandlinetools.zip -d $HOME/android
        rm commandlinetools.zip

        # Install the necessary SDK components
        yes | $HOME/android/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/android --update
        yes | $HOME/android/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/android "platform-tools"
        yes | $HOME/android/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/android "platforms;android-29"
        yes | $HOME/android/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/android "ndk;21.3.6528147"
        yes | $HOME/android/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/android "build-tools;29.0.3"

        # Set up environment variables for Android SDK/NDK
        echo "ANDROID_HOME=$HOME/android" >> $GITHUB_ENV
        echo "ANDROID_NDK=$HOME/android/ndk/21.3.6528147" >> $GITHUB_ENV
        echo "JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64" >> $GITHUB_ENV  # Set JAVA_HOME to OpenJDK 8

    - name: Set up Buildozer spec file
      run: |
        # Copy your buildozer.spec file to the workspace if needed
        cp path/to/your/buildozer.spec $GITHUB_WORKSPACE/

    - name: Build the app using Buildozer
      run: |
        buildozer android debug

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v2
      with:
        name: android-apk
        path: bin/*.apk
