name: Build Android App with Buildozer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install required dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip python3-dev build-essential curl unzip
        sudo apt-get install -y openjdk-8-jdk  # Installing OpenJDK 8 for compatibility

    - name: Install Cython
      run: |
        python3 -m pip install cython  # Install Cython here

    - name: Install Buildozer and dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install buildozer

    - name: Install Android SDK and NDK
      run: |
        # Install Android SDK command-line tools
        curl -sS https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -o commandlinetools.zip
        mkdir -p $HOME/android/cmdline-tools/latest
        unzip commandlinetools.zip -d $HOME/android/cmdline-tools/latest
        rm commandlinetools.zip

        # Accept all Android SDK licenses automatically
        yes | $HOME/android/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android --licenses
        
        # Install required SDK components
        yes | $HOME/android/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android --update
        yes | $HOME/android/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android "platform-tools"
        yes | $HOME/android/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android "platforms;android-31"
        yes | $HOME/android/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android "build-tools;31.0.0"

        # Install a compatible NDK version (e.g., 21.3.6528147)
        yes | $HOME/android/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android "ndk;21.3.6528147"

        # Install aidl (now part of the SDK tools)
        yes | $HOME/android/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android "cmdline-tools;latest"
        
        # Verify aidl installation
        if [ ! -f $HOME/android/cmdline-tools/latest/bin/aidl ]; then
          echo "AIDL installation failed"
          exit 1
        fi

        # Set up environment variables for Android SDK/NDK
        echo "ANDROID_HOME=$HOME/android" >> $GITHUB_ENV
        echo "ANDROID_NDK=$HOME/android/ndk/21.3.6528147" >> $GITHUB_ENV
        echo "JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64" >> $GITHUB_ENV  # Set JAVA_HOME to OpenJDK 8

    - name: Build the app using Buildozer
      run: |
        buildozer android debug

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v3
      with:
        name: android-apk
        path: bin/*.apk
